let mijnVoornaam = "Bruno";
let mijnAchternaam="Hofman";
let leeftijd = 15;
let stemgerechtig = false;
let legaalalcoholkopen= false;
let brommerrijden = false;
let softwareOntwikkeling = true;
console.log(mijnVoornaam);
console.log(mijnAchternaam);
console.log(leeftijd);
console.log(stemgerechtig);
console.log(legaalalcoholkopen);
console.log(brommerrijden);
console.log(softwareOntwikkeling);